---
# defaults file for microk8s-server

# MicroK8S version to install
microk8s_version: 1.24/stable

# Designate whether High Availability will be enabled for this cluster (3 node minimum)
microk8s_enable_ha: false

# Group defined in your hosts inventory file that contains High Availability members. Used if enabling High Availability.
microk8s_host_ha_group: microk8s-ha-group

# Group defined in your hosts inventory file that contains the primary node if not enabling High Availability, but adding worker nodes.
microk8s_host_primary_group: microk8s-primary

# Add worker nodes to hosts file entries if using worker nodes
microk8s_host_workers_group: microk8s-workers

# If DNS is not available you can optionally add cluster members to each nodes hosts file.
add_cluster_members_to_hosts_file: true
add_workers_to_hosts_file: false

# Users that will be setup to use microk8s.
# Adds to microk8s group, creates kube config, enables helm repositories
users: ['vagrant']

# Helm3 repositories to add for each user (if Microk8s helm3 addon enabled)
helm3_repositories:
  - name: stable
    url: https://charts.helm.sh/stable

# MicroK8s Plug-ins
microk8s_dns_resolvers: 192.168.1.1      # Adjust to your network
registry_size: 20Gi
metallb_ip_range: 192.168.1.150-192.168.1.160  # Adjust to your nodes IP range. Metallb will assign IP's from this range.
microk8s_plugins:
  dns: "{{ microk8s_dns_resolvers }}"     # CoreDNS
  host-access: true                       # Allow Pods connecting to Host services smoothly
  ingress: true                           # Ingress controller for external access
  metrics-server: true                    # K8s Metrics Server for API access to service metrics
  rbac: true                              # Role-Based Access Control for authorisation
  storage: true                           # Storage class; allocates storage from host directory
  registry: "size={{ registry_size }}"    # Private image registry exposed on localhost:32000
  dashboard: true                         # The Kubernetes dashboard
  ambassador: false                       # Ambassador API Gateway and Ingress
  cilium: false                           # SDN, fast with full network policy
  fluentd: false                          # Elasticsearch-Fluentd-Kibana logging and monitoring
  gpu: false                              # Automatic enablement of Nvidia CUDA
  helm: false                             # Helm 2 - the package manager for Kubernetes
  helm3: true                             # Helm 3 - Kubernetes package manager
  istio: false                            # Core Istio service mesh services
  jaeger: false                           # Kubernetes Jaeger operator with its simple config
  knative: false                          # The Knative framework on Kubernetes.
  kubeflow: false                         # Kubeflow for easy ML deployments
  linkerd: false                          # Linkerd is a service mesh for Kubernetes and other frameworks
  metallb: "{{ metallb_ip_range }}"       # Loadbalancer for your Kubernetes cluster
  multus: false                           # Multus CNI enables attaching multiple network interfaces to pods
  prometheus: false                       # Prometheus operator for monitoring and logging
  traefik: false                          # another ingress
  portainer: false                        # Container management dashboard
  keda: false                             # Kubernetes Event-driven Autoscaling operator.
  kata: false                             # A secure container runtime with lightweight virtual machines
  openebs: false                          # openebs storage
  openfaas: false                         # serverless

# Regex string to match the format of an IP address
microk8s_ha_ip_regex: "([0-9]{1,3}[\\.]){3}[0-9]{1,3}"