# If users are defined and helm3 is enabled on MicroK8s
# add and update helm repositories defined in variables file
# to each defined user.
---
- name: Add helm repositories for user (if microk8s helm addon enabled)
  become: yes
  become_user: '{{ item.0 }}'
  shell: "helm repo add {{ item.1.name }} {{ item.1.url }}"
  args:
    executable: /bin/bash
  changed_when: true
  with_nested:
    - "{{ users }}"
    - "{{ helm3_repositories }}"
  when: microk8s_plugins.helm3

- name: Update helm repositories for user (if microk8s helm addon enabled)
  become: yes
  become_user: '{{ user }}'
  shell: "helm repo update"
  args:
    executable: /bin/bash
  changed_when: true
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
  when: microk8s_plugins.helm3